// Compiles a dart2wasm-generated main module from `source` which can then
// instantiatable via the `instantiate` method.
//
// `source` needs to be a `Response` object (or promise thereof) e.g. created
// via the `fetch()` JS API.
export async function compileStreaming(source) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(
      await WebAssembly.compileStreaming(source, builtins), builtins);
}

// Compiles a dart2wasm-generated wasm modules from `bytes` which is then
// instantiatable via the `instantiate` method.
export async function compile(bytes) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(await WebAssembly.compile(bytes, builtins), builtins);
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export async function instantiate(modulePromise, importObjectPromise) {
  var moduleOrCompiledApp = await modulePromise;
  if (!(moduleOrCompiledApp instanceof CompiledApp)) {
    moduleOrCompiledApp = new CompiledApp(moduleOrCompiledApp);
  }
  const instantiatedApp = await moduleOrCompiledApp.instantiate(await importObjectPromise);
  return instantiatedApp.instantiatedModule;
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export const invoke = (moduleInstance, ...args) => {
  moduleInstance.exports.$invokeMain(args);
}

class CompiledApp {
  constructor(module, builtins) {
    this.module = module;
    this.builtins = builtins;
  }

  // The second argument is an options object containing:
  // `loadDeferredModule` is a JS function that takes a module name matching a
  //   wasm file produced by the dart2wasm compiler and returns the bytes to
  //   load the module. These bytes can be in either a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  // `loadDynamicModule` is a JS function that takes two string names matching,
  //   in order, a wasm file produced by the dart2wasm compiler during dynamic
  //   module compilation and a corresponding js file produced by the same
  //   compilation. It should return a JS Array containing 2 elements. The first
  //   should be the bytes for the wasm module in a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`. The second
  //   should be the result of using the JS 'import' API on the js file path.
  // `loadDeferredId` is a JS function that takes a string corresponding to a load
  //   ID generated by the compiler when 'load-ids' option is passed. Each load
  //   ID maps to one or more WASM modules produced by the compiler. This
  //   function should return an array of byte arrays corresponding to all the
  //   modules specified by that load ID. The arrays should be in a format
  //   supported by `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  async instantiate(additionalImports,
      {loadDeferredModule, loadDynamicModule, loadDeferredId} = {}) {
    let dartInstance;

    // Prints to the console
    function printToConsole(value) {
      if (typeof dartPrint == "function") {
        dartPrint(value);
        return;
      }
      if (typeof console == "object" && typeof console.log != "undefined") {
        console.log(value);
        return;
      }
      if (typeof print == "function") {
        print(value);
        return;
      }

      throw "Unable to print message: " + value;
    }

    // A special symbol attached to functions that wrap Dart functions.
    const jsWrappedDartFunctionSymbol = Symbol("JSWrappedDartFunction");

    function finalizeWrapper(dartFunction, wrapped) {
      wrapped.dartFunction = dartFunction;
      wrapped[jsWrappedDartFunctionSymbol] = true;
      return wrapped;
    }

    // Imports
    const dart2wasm = {
            _1: (decoder, codeUnits) => decoder.decode(codeUnits),
      _2: () => new TextDecoder("utf-8", {fatal: true}),
      _3: () => new TextDecoder("utf-8", {fatal: false}),
      _4: (s) => +s,
      _5: x0 => new Uint8Array(x0),
      _6: (x0,x1,x2) => x0.set(x1,x2),
      _7: (x0,x1) => x0.transferFromImageBitmap(x1),
      _8: x0 => x0.arrayBuffer(),
      _9: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._9(f,arguments.length,x0) }),
      _10: x0 => new window.FinalizationRegistry(x0),
      _11: (x0,x1,x2,x3) => x0.register(x1,x2,x3),
      _12: (x0,x1) => x0.unregister(x1),
      _13: (x0,x1,x2) => x0.slice(x1,x2),
      _14: (x0,x1) => x0.decode(x1),
      _15: (x0,x1) => x0.segment(x1),
      _16: () => new TextDecoder(),
      _18: x0 => x0.buffer,
      _19: x0 => x0.wasmMemory,
      _20: () => globalThis.window._flutter_skwasmInstance,
      _21: x0 => x0.rasterStartMilliseconds,
      _22: x0 => x0.rasterEndMilliseconds,
      _23: x0 => x0.imageBitmaps,
      _139: (x0,x1) => x0.appendChild(x1),
      _170: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _171: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _172: (x0,x1) => new OffscreenCanvas(x0,x1),
      _173: x0 => x0.remove(),
      _174: (x0,x1) => x0.append(x1),
      _176: x0 => x0.unlock(),
      _177: x0 => x0.getReader(),
      _178: (x0,x1) => x0.item(x1),
      _179: x0 => x0.next(),
      _180: x0 => x0.now(),
      _181: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._181(f,arguments.length,x0) }),
      _182: (x0,x1) => x0.addListener(x1),
      _183: (x0,x1) => x0.removeListener(x1),
      _184: (x0,x1) => x0.matchMedia(x1),
      _185: (x0,x1) => x0.revokeObjectURL(x1),
      _186: x0 => x0.close(),
      _187: (x0,x1,x2,x3,x4) => ({type: x0,data: x1,premultiplyAlpha: x2,colorSpaceConversion: x3,preferAnimation: x4}),
      _188: x0 => new window.ImageDecoder(x0),
      _189: (x0,x1) => ({frameIndex: x0,completeFramesOnly: x1}),
      _190: (x0,x1) => x0.decode(x1),
      _191: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._191(f,arguments.length,x0) }),
      _192: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _194: (x0,x1) => x0.getModifierState(x1),
      _195: x0 => x0.preventDefault(),
      _196: x0 => x0.stopPropagation(),
      _197: (x0,x1) => x0.removeProperty(x1),
      _198: (x0,x1) => x0.prepend(x1),
      _199: x0 => new Intl.Locale(x0),
      _200: (x0,x1) => x0.observe(x1),
      _201: x0 => x0.disconnect(),
      _202: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._202(f,arguments.length,x0) }),
      _203: (x0,x1) => x0.getAttribute(x1),
      _204: (x0,x1) => x0.contains(x1),
      _205: (x0,x1) => x0.querySelector(x1),
      _206: x0 => x0.blur(),
      _207: x0 => x0.hasFocus(),
      _208: (x0,x1) => x0.removeAttribute(x1),
      _209: (x0,x1,x2) => x0.insertBefore(x1,x2),
      _210: (x0,x1) => x0.hasAttribute(x1),
      _211: (x0,x1) => x0.getModifierState(x1),
      _212: (x0,x1) => x0.createTextNode(x1),
      _213: x0 => x0.getBoundingClientRect(),
      _214: (x0,x1) => x0.closest(x1),
      _215: () => new Array(),
      _651: x0 => new Uint8Array(x0),
      _655: () => globalThis.window.flutterConfiguration,
      _657: x0 => x0.assetBase,
      _662: x0 => x0.canvasKitMaximumSurfaces,
      _663: x0 => x0.debugShowSemanticsNodes,
      _664: x0 => x0.hostElement,
      _665: x0 => x0.multiViewEnabled,
      _666: x0 => x0.nonce,
      _668: x0 => x0.fontFallbackBaseUrl,
      _678: x0 => x0.console,
      _679: x0 => x0.devicePixelRatio,
      _680: x0 => x0.document,
      _681: x0 => x0.history,
      _682: x0 => x0.innerHeight,
      _683: x0 => x0.innerWidth,
      _684: x0 => x0.location,
      _685: x0 => x0.navigator,
      _686: x0 => x0.visualViewport,
      _687: x0 => x0.performance,
      _689: x0 => x0.URL,
      _691: (x0,x1) => x0.getComputedStyle(x1),
      _692: x0 => x0.screen,
      _693: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._693(f,arguments.length,x0) }),
      _694: (x0,x1) => x0.requestAnimationFrame(x1),
      _698: (x0,x1) => x0.warn(x1),
      _700: (x0,x1) => x0.debug(x1),
      _701: x0 => globalThis.parseFloat(x0),
      _702: () => globalThis.window,
      _703: () => globalThis.Intl,
      _704: () => globalThis.Symbol,
      _705: (x0,x1,x2,x3,x4) => globalThis.createImageBitmap(x0,x1,x2,x3,x4),
      _707: x0 => x0.clipboard,
      _708: x0 => x0.maxTouchPoints,
      _709: x0 => x0.vendor,
      _710: x0 => x0.language,
      _711: x0 => x0.platform,
      _712: x0 => x0.userAgent,
      _713: (x0,x1) => x0.vibrate(x1),
      _714: x0 => x0.languages,
      _715: x0 => x0.documentElement,
      _716: (x0,x1) => x0.querySelector(x1),
      _717: (x0,x1) => x0.querySelectorAll(x1),
      _719: (x0,x1) => x0.createElement(x1),
      _722: (x0,x1) => x0.createEvent(x1),
      _723: x0 => x0.activeElement,
      _726: x0 => x0.head,
      _727: x0 => x0.body,
      _728: (x0,x1) => { x0.title = x1 },
      _732: x0 => x0.visibilityState,
      _733: () => globalThis.document,
      _734: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._734(f,arguments.length,x0) }),
      _735: (x0,x1) => x0.dispatchEvent(x1),
      _743: x0 => x0.target,
      _745: x0 => x0.timeStamp,
      _746: x0 => x0.type,
      _748: (x0,x1,x2,x3) => x0.initEvent(x1,x2,x3),
      _755: x0 => x0.firstChild,
      _759: x0 => x0.parentElement,
      _761: (x0,x1) => { x0.textContent = x1 },
      _762: x0 => x0.parentNode,
      _763: x0 => x0.nextSibling,
      _764: (x0,x1) => x0.removeChild(x1),
      _765: x0 => x0.isConnected,
      _773: x0 => x0.clientHeight,
      _774: x0 => x0.clientWidth,
      _775: x0 => x0.offsetHeight,
      _776: x0 => x0.offsetWidth,
      _777: x0 => x0.id,
      _778: (x0,x1) => { x0.id = x1 },
      _781: (x0,x1) => { x0.spellcheck = x1 },
      _782: x0 => x0.tagName,
      _783: x0 => x0.style,
      _786: (x0,x1) => x0.querySelectorAll(x1),
      _787: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _788: (x0,x1) => { x0.tabIndex = x1 },
      _789: x0 => x0.tabIndex,
      _790: (x0,x1) => x0.focus(x1),
      _791: x0 => x0.scrollTop,
      _792: (x0,x1) => { x0.scrollTop = x1 },
      _793: x0 => x0.scrollLeft,
      _794: (x0,x1) => { x0.scrollLeft = x1 },
      _795: x0 => x0.classList,
      _797: (x0,x1) => { x0.className = x1 },
      _799: (x0,x1) => x0.getElementsByClassName(x1),
      _800: x0 => x0.click(),
      _801: (x0,x1) => x0.attachShadow(x1),
      _804: x0 => x0.computedStyleMap(),
      _805: (x0,x1) => x0.get(x1),
      _811: (x0,x1) => x0.getPropertyValue(x1),
      _812: (x0,x1,x2,x3) => x0.setProperty(x1,x2,x3),
      _813: x0 => x0.offsetLeft,
      _814: x0 => x0.offsetTop,
      _815: x0 => x0.offsetParent,
      _817: (x0,x1) => { x0.name = x1 },
      _818: x0 => x0.content,
      _819: (x0,x1) => { x0.content = x1 },
      _823: (x0,x1) => { x0.src = x1 },
      _824: x0 => x0.naturalWidth,
      _825: x0 => x0.naturalHeight,
      _829: (x0,x1) => { x0.crossOrigin = x1 },
      _831: (x0,x1) => { x0.decoding = x1 },
      _832: x0 => x0.decode(),
      _837: (x0,x1) => { x0.nonce = x1 },
      _841: (x0,x1) => { x0.width = x1 },
      _844: (x0,x1) => { x0.height = x1 },
      _847: (x0,x1) => x0.getContext(x1),
      _914: x0 => x0.width,
      _915: x0 => x0.height,
      _917: (x0,x1) => x0.fetch(x1),
      _918: x0 => x0.status,
      _920: x0 => x0.body,
      _921: x0 => x0.arrayBuffer(),
      _924: x0 => x0.read(),
      _925: x0 => x0.value,
      _926: x0 => x0.done,
      _933: x0 => x0.name,
      _934: x0 => x0.x,
      _935: x0 => x0.y,
      _938: x0 => x0.top,
      _939: x0 => x0.right,
      _940: x0 => x0.bottom,
      _941: x0 => x0.left,
      _951: x0 => x0.height,
      _952: x0 => x0.width,
      _953: x0 => x0.scale,
      _954: (x0,x1) => { x0.value = x1 },
      _957: (x0,x1) => { x0.placeholder = x1 },
      _959: (x0,x1) => { x0.name = x1 },
      _960: x0 => x0.selectionDirection,
      _961: x0 => x0.selectionStart,
      _962: x0 => x0.selectionEnd,
      _965: x0 => x0.value,
      _967: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _968: x0 => x0.readText(),
      _969: (x0,x1) => x0.writeText(x1),
      _971: x0 => x0.altKey,
      _972: x0 => x0.code,
      _973: x0 => x0.ctrlKey,
      _974: x0 => x0.key,
      _975: x0 => x0.keyCode,
      _976: x0 => x0.location,
      _977: x0 => x0.metaKey,
      _978: x0 => x0.repeat,
      _979: x0 => x0.shiftKey,
      _980: x0 => x0.isComposing,
      _982: x0 => x0.state,
      _983: (x0,x1) => x0.go(x1),
      _985: (x0,x1,x2,x3) => x0.pushState(x1,x2,x3),
      _986: (x0,x1,x2,x3) => x0.replaceState(x1,x2,x3),
      _987: x0 => x0.pathname,
      _988: x0 => x0.search,
      _989: x0 => x0.hash,
      _993: x0 => x0.state,
      _996: (x0,x1) => x0.createObjectURL(x1),
      _998: x0 => new Blob(x0),
      _1008: x0 => x0.matches,
      _1009: x0 => x0.matches,
      _1013: x0 => x0.relatedTarget,
      _1015: x0 => x0.clientX,
      _1016: x0 => x0.clientY,
      _1017: x0 => x0.offsetX,
      _1018: x0 => x0.offsetY,
      _1021: x0 => x0.button,
      _1022: x0 => x0.buttons,
      _1023: x0 => x0.ctrlKey,
      _1027: x0 => x0.pointerId,
      _1028: x0 => x0.pointerType,
      _1029: x0 => x0.pressure,
      _1030: x0 => x0.tiltX,
      _1031: x0 => x0.tiltY,
      _1032: x0 => x0.getCoalescedEvents(),
      _1035: x0 => x0.deltaX,
      _1036: x0 => x0.deltaY,
      _1037: x0 => x0.wheelDeltaX,
      _1038: x0 => x0.wheelDeltaY,
      _1039: x0 => x0.deltaMode,
      _1046: x0 => x0.changedTouches,
      _1049: x0 => x0.clientX,
      _1050: x0 => x0.clientY,
      _1053: x0 => x0.data,
      _1056: (x0,x1) => { x0.disabled = x1 },
      _1058: (x0,x1) => { x0.type = x1 },
      _1059: (x0,x1) => { x0.max = x1 },
      _1060: (x0,x1) => { x0.min = x1 },
      _1061: (x0,x1) => { x0.value = x1 },
      _1062: x0 => x0.value,
      _1063: x0 => x0.disabled,
      _1064: (x0,x1) => { x0.disabled = x1 },
      _1066: (x0,x1) => { x0.placeholder = x1 },
      _1068: (x0,x1) => { x0.name = x1 },
      _1069: (x0,x1) => { x0.autocomplete = x1 },
      _1071: x0 => x0.selectionDirection,
      _1072: x0 => x0.selectionStart,
      _1074: x0 => x0.selectionEnd,
      _1077: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _1078: (x0,x1) => x0.add(x1),
      _1081: (x0,x1) => { x0.noValidate = x1 },
      _1082: (x0,x1) => { x0.method = x1 },
      _1083: (x0,x1) => { x0.action = x1 },
      _1089: (x0,x1) => x0.getContext(x1),
      _1091: x0 => x0.convertToBlob(),
      _1108: x0 => x0.orientation,
      _1109: x0 => x0.width,
      _1110: x0 => x0.height,
      _1111: (x0,x1) => x0.lock(x1),
      _1130: x0 => new ResizeObserver(x0),
      _1133: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1133(f,arguments.length,x0,x1) }),
      _1141: x0 => x0.length,
      _1142: x0 => x0.iterator,
      _1143: x0 => x0.Segmenter,
      _1144: x0 => x0.v8BreakIterator,
      _1145: (x0,x1) => new Intl.Segmenter(x0,x1),
      _1148: x0 => x0.language,
      _1149: x0 => x0.script,
      _1150: x0 => x0.region,
      _1168: x0 => x0.done,
      _1169: x0 => x0.value,
      _1170: x0 => x0.index,
      _1174: (x0,x1) => new Intl.v8BreakIterator(x0,x1),
      _1175: (x0,x1) => x0.adoptText(x1),
      _1176: x0 => x0.first(),
      _1177: x0 => x0.next(),
      _1178: x0 => x0.current(),
      _1191: x0 => x0.hostElement,
      _1192: x0 => x0.viewConstraints,
      _1195: x0 => x0.maxHeight,
      _1196: x0 => x0.maxWidth,
      _1197: x0 => x0.minHeight,
      _1198: x0 => x0.minWidth,
      _1199: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1199(f,arguments.length,x0) }),
      _1200: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1200(f,arguments.length,x0) }),
      _1201: (x0,x1) => ({addView: x0,removeView: x1}),
      _1204: x0 => x0.loader,
      _1205: () => globalThis._flutter,
      _1206: (x0,x1) => x0.didCreateEngineInitializer(x1),
      _1207: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1207(f,arguments.length,x0) }),
      _1208: (module,f) => finalizeWrapper(f, function() { return module.exports._1208(f,arguments.length) }),
      _1209: (x0,x1) => ({initializeEngine: x0,autoStart: x1}),
      _1212: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1212(f,arguments.length,x0) }),
      _1213: x0 => ({runApp: x0}),
      _1215: (x0,x1,x2) => x0.call(x1,x2),
      _1216: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1216(f,arguments.length,x0,x1) }),
      _1217: x0 => new Promise(x0),
      _1218: x0 => x0.length,
      _1219: () => globalThis.window.ImageDecoder,
      _1220: x0 => x0.tracks,
      _1222: x0 => x0.completed,
      _1224: x0 => x0.image,
      _1230: x0 => x0.displayWidth,
      _1231: x0 => x0.displayHeight,
      _1232: x0 => x0.duration,
      _1235: x0 => x0.ready,
      _1236: x0 => x0.selectedTrack,
      _1237: x0 => x0.repetitionCount,
      _1238: x0 => x0.frameCount,
      _1286: (x0,x1) => x0.createElement(x1),
      _1292: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1293: x0 => x0.remove(),
      _1295: x0 => ({createScriptURL: x0}),
      _1296: (x0,x1,x2) => x0.createPolicy(x1,x2),
      _1300: (x0,x1) => x0.append(x1),
      _1301: (x0,x1) => x0.querySelectorAll(x1),
      _1302: (x0,x1) => x0.item(x1),
      _1320: x0 => ({type: x0}),
      _1321: (x0,x1) => new Blob(x0,x1),
      _1322: x0 => globalThis.URL.createObjectURL(x0),
      _1323: (x0,x1) => x0.getElementById(x1),
      _1324: (x0,x1) => x0.createElement(x1),
      _1325: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _1326: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _1327: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1327(f,arguments.length,x0) }),
      _1328: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1329: x0 => x0.click(),
      _1330: () => ({}),
      _1331: x0 => globalThis.pdfjsLib.getDocument(x0),
      _1332: (x0,x1) => x0.getContext(x1),
      _1333: (x0,x1) => x0.getPage(x1),
      _1334: (x0,x1) => x0.getViewport(x1),
      _1335: (x0,x1) => x0.render(x1),
      _1336: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1336(f,arguments.length,x0) }),
      _1337: (x0,x1) => x0.toBlob(x1),
      _1338: () => new FileReader(),
      _1339: (x0,x1) => x0.readAsArrayBuffer(x1),
      _1340: x0 => x0.cleanup(),
      _1341: x0 => x0.destroy(),
      _1342: (x0,x1) => { x0.module = x1 },
      _1343: (x0,x1) => { x0.exports = x1 },
      _1344: x0 => x0.preventDefault(),
      _1345: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _1346: (x0,x1,x2,x3) => x0.removeEventListener(x1,x2,x3),
      _1348: (x0,x1) => x0.getAttribute(x1),
      _1352: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1374: x0 => globalThis.URL.revokeObjectURL(x0),
      _1379: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1379(f,arguments.length,x0) }),
      _1380: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1380(f,arguments.length,x0) }),
      _1381: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1381(f,arguments.length,x0) }),
      _1382: (x0,x1) => x0.querySelector(x1),
      _1383: (x0,x1) => x0.replaceChildren(x1),
      _1393: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1393(f,arguments.length,x0) }),
      _1394: (x0,x1) => x0.readEntries(x1),
      _1395: x0 => x0.createReader(),
      _1396: () => new Blob(),
      _1397: (x0,x1,x2,x3) => x0.slice(x1,x2,x3),
      _1398: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1398(f,arguments.length,x0) }),
      _1399: (x0,x1) => x0.file(x1),
      _1400: x0 => x0.webkitGetAsEntry(),
      _1401: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1401(f,arguments.length,x0) }),
      _1402: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1402(f,arguments.length,x0) }),
      _1403: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1403(f,arguments.length,x0) }),
      _1404: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1404(f,arguments.length,x0) }),
      _1406: (x0,x1) => x0.item(x1),
      _1408: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1408(f,arguments.length,x0) }),
      _1409: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1409(f,arguments.length,x0) }),
      _1410: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1410(f,arguments.length,x0) }),
      _1411: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1411(f,arguments.length,x0) }),
      _1412: (x0,x1) => x0.removeChild(x1),
      _1413: x0 => new Blob(x0),
      _1415: x0 => x0.decode(),
      _1416: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1417: (x0,x1,x2) => x0.setRequestHeader(x1,x2),
      _1418: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1418(f,arguments.length,x0) }),
      _1419: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1419(f,arguments.length,x0) }),
      _1420: x0 => x0.send(),
      _1421: () => new XMLHttpRequest(),
      _1422: (x0,x1) => x0.getItem(x1),
      _1423: (x0,x1,x2) => x0.setItem(x1,x2),
      _1424: (x0,x1) => x0.removeItem(x1),
      _1434: () => globalThis.removeSplashFromWeb(),
      _1436: (x0,x1) => x0.initialize(x1),
      _1437: (x0,x1) => x0.initTokenClient(x1),
      _1441: Date.now,
      _1443: s => new Date(s * 1000).getTimezoneOffset() * 60,
      _1444: s => {
        if (!/^\s*[+-]?(?:Infinity|NaN|(?:\.\d+|\d+(?:\.\d*)?)(?:[eE][+-]?\d+)?)\s*$/.test(s)) {
          return NaN;
        }
        return parseFloat(s);
      },
      _1445: () => new Error().stack,
      _1446: () => typeof dartUseDateNowForTicks !== "undefined",
      _1447: () => 1000 * performance.now(),
      _1448: () => Date.now(),
      _1449: () => {
        // On browsers return `globalThis.location.href`
        if (globalThis.location != null) {
          return globalThis.location.href;
        }
        return null;
      },
      _1450: () => {
        return typeof process != "undefined" &&
               Object.prototype.toString.call(process) == "[object process]" &&
               process.platform == "win32"
      },
      _1451: () => new WeakMap(),
      _1452: (map, o) => map.get(o),
      _1453: (map, o, v) => map.set(o, v),
      _1454: (exn) => exn.toString(),
      _1455: (exn) => exn.stack,
      _1456: (exn) => {
        let stackString = exn.toString();
        let frames = stackString.split('\n');
        let drop = 2;
        if (frames[0] === 'Error') {
            drop += 1;
        }
        return frames.slice(drop).join('\n');
      },
      _1457: x0 => new WeakRef(x0),
      _1458: x0 => x0.deref(),
      _1459: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1459(f,arguments.length,x0) }),
      _1460: x0 => new FinalizationRegistry(x0),
      _1461: (x0,x1,x2,x3) => x0.register(x1,x2,x3),
      _1463: (x0,x1) => x0.unregister(x1),
      _1465: () => globalThis.WeakRef,
      _1466: () => globalThis.FinalizationRegistry,
      _1468: x0 => x0.call(),
      _1469: s => JSON.stringify(s),
      _1470: s => printToConsole(s),
      _1471: (o, p, r) => o.replaceAll(p, () => r),
      _1472: (o, p, r) => o.replace(p, () => r),
      _1473: Function.prototype.call.bind(String.prototype.toLowerCase),
      _1474: s => s.toUpperCase(),
      _1475: s => s.trim(),
      _1476: s => s.trimLeft(),
      _1477: s => s.trimRight(),
      _1478: (string, times) => string.repeat(times),
      _1479: Function.prototype.call.bind(String.prototype.indexOf),
      _1480: (s, p, i) => s.lastIndexOf(p, i),
      _1481: (string, token) => string.split(token),
      _1482: Object.is,
      _1485: (o, t) => typeof o === t,
      _1486: (o, c) => o instanceof c,
      _1487: o => Object.keys(o),
      _1490: (o, a) => o + a,
      _1500: (o, a) => o == a,
      _1517: x0 => new Array(x0),
      _1519: x0 => x0.length,
      _1521: (x0,x1) => x0[x1],
      _1522: (x0,x1,x2) => { x0[x1] = x2 },
      _1525: (x0,x1,x2) => new DataView(x0,x1,x2),
      _1527: x0 => new Int8Array(x0),
      _1528: (x0,x1,x2) => new Uint8Array(x0,x1,x2),
      _1530: x0 => new Uint8ClampedArray(x0),
      _1532: x0 => new Int16Array(x0),
      _1534: x0 => new Uint16Array(x0),
      _1536: x0 => new Int32Array(x0),
      _1538: x0 => new Uint32Array(x0),
      _1540: x0 => new Float32Array(x0),
      _1542: x0 => new Float64Array(x0),
      _1566: x0 => x0.random(),
      _1567: (x0,x1) => x0.getRandomValues(x1),
      _1568: () => globalThis.crypto,
      _1569: () => globalThis.Math,
      _1582: (ms, c) =>
      setTimeout(() => dartInstance.exports.$invokeCallback(c),ms),
      _1583: (handle) => clearTimeout(handle),
      _1584: (ms, c) =>
      setInterval(() => dartInstance.exports.$invokeCallback(c), ms),
      _1585: (handle) => clearInterval(handle),
      _1586: (c) =>
      queueMicrotask(() => dartInstance.exports.$invokeCallback(c)),
      _1587: () => Date.now(),
      _1588: (s, m) => {
        try {
          return new RegExp(s, m);
        } catch (e) {
          return String(e);
        }
      },
      _1589: (x0,x1) => x0.exec(x1),
      _1590: (x0,x1) => x0.test(x1),
      _1591: x0 => x0.pop(),
      _1593: o => o === undefined,
      _1595: o => typeof o === 'function' && o[jsWrappedDartFunctionSymbol] === true,
      _1597: o => {
        const proto = Object.getPrototypeOf(o);
        return proto === Object.prototype || proto === null;
      },
      _1598: o => o instanceof RegExp,
      _1599: (l, r) => l === r,
      _1600: o => o,
      _1601: o => o,
      _1602: o => o,
      _1603: b => !!b,
      _1604: o => o.length,
      _1606: (o, i) => o[i],
      _1607: f => f.dartFunction,
      _1608: () => ({}),
      _1609: () => [],
      _1611: () => globalThis,
      _1612: (constructor, args) => {
        const factoryFunction = constructor.bind.apply(
            constructor, [null, ...args]);
        return new factoryFunction();
      },
      _1613: (o, p) => p in o,
      _1614: (o, p) => o[p],
      _1615: (o, p, v) => o[p] = v,
      _1616: (o, m, a) => o[m].apply(o, a),
      _1618: o => String(o),
      _1619: (p, s, f) => p.then(s, (e) => f(e, e === undefined)),
      _1620: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1620(f,arguments.length,x0) }),
      _1621: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1621(f,arguments.length,x0,x1) }),
      _1622: o => {
        if (o === undefined) return 1;
        var type = typeof o;
        if (type === 'boolean') return 2;
        if (type === 'number') return 3;
        if (type === 'string') return 4;
        if (o instanceof Array) return 5;
        if (ArrayBuffer.isView(o)) {
          if (o instanceof Int8Array) return 6;
          if (o instanceof Uint8Array) return 7;
          if (o instanceof Uint8ClampedArray) return 8;
          if (o instanceof Int16Array) return 9;
          if (o instanceof Uint16Array) return 10;
          if (o instanceof Int32Array) return 11;
          if (o instanceof Uint32Array) return 12;
          if (o instanceof Float32Array) return 13;
          if (o instanceof Float64Array) return 14;
          if (o instanceof DataView) return 15;
        }
        if (o instanceof ArrayBuffer) return 16;
        // Feature check for `SharedArrayBuffer` before doing a type-check.
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
            return 17;
        }
        if (o instanceof Promise) return 18;
        return 19;
      },
      _1623: o => [o],
      _1624: (o0, o1) => [o0, o1],
      _1625: (o0, o1, o2) => [o0, o1, o2],
      _1626: (o0, o1, o2, o3) => [o0, o1, o2, o3],
      _1627: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI8ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1628: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI8ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1629: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI16ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1630: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI16ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1631: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1632: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1633: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1634: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1635: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF64ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1636: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF64ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1637: x0 => new ArrayBuffer(x0),
      _1638: s => {
        if (/[[\]{}()*+?.\\^$|]/.test(s)) {
            s = s.replace(/[[\]{}()*+?.\\^$|]/g, '\\$&');
        }
        return s;
      },
      _1639: x0 => x0.input,
      _1640: x0 => x0.index,
      _1641: x0 => x0.groups,
      _1642: x0 => x0.flags,
      _1643: x0 => x0.multiline,
      _1644: x0 => x0.ignoreCase,
      _1645: x0 => x0.unicode,
      _1646: x0 => x0.dotAll,
      _1647: (x0,x1) => { x0.lastIndex = x1 },
      _1648: (o, p) => p in o,
      _1649: (o, p) => o[p],
      _1650: (o, p, v) => o[p] = v,
      _1652: x0 => x0.arrayBuffer(),
      _1653: (x0,x1) => x0.sqlite3changeset_finalize(x1),
      _1654: (x0,x1) => x0.sqlite3session_delete(x1),
      _1655: (x0,x1) => x0.sqlite3_close_v2(x1),
      _1656: (x0,x1) => x0.sqlite3_finalize(x1),
      _1657: (x0,x1) => x0.dart_sqlite3_malloc(x1),
      _1658: (x0,x1) => x0.dart_sqlite3_free(x1),
      _1660: x0 => x0.sqlite3_initialize(),
      _1666: (x0,x1,x2,x3,x4) => x0.sqlite3_open_v2(x1,x2,x3,x4),
      _1667: (x0,x1) => x0.sqlite3_extended_errcode(x1),
      _1668: (x0,x1) => x0.sqlite3_errmsg(x1),
      _1669: (x0,x1) => x0.sqlite3_errstr(x1),
      _1670: (x0,x1) => x0.sqlite3_error_offset(x1),
      _1671: (x0,x1,x2) => x0.sqlite3_extended_result_codes(x1,x2),
      _1672: (x0,x1,x2) => x0.dart_sqlite3_updates(x1,x2),
      _1673: (x0,x1,x2) => x0.dart_sqlite3_commits(x1,x2),
      _1674: (x0,x1,x2) => x0.dart_sqlite3_rollbacks(x1,x2),
      _1675: (x0,x1,x2,x3,x4,x5) => x0.sqlite3_exec(x1,x2,x3,x4,x5),
      _1676: (x0,x1,x2,x3,x4,x5,x6) => x0.sqlite3_prepare_v3(x1,x2,x3,x4,x5,x6),
      _1677: (x0,x1) => x0.sqlite3_bind_parameter_count(x1),
      _1678: (x0,x1,x2) => x0.sqlite3_bind_null(x1,x2),
      _1679: (x0,x1,x2,x3) => x0.sqlite3_bind_int64(x1,x2,x3),
      _1680: (x0,x1,x2,x3) => x0.sqlite3_bind_double(x1,x2,x3),
      _1681: (x0,x1,x2,x3,x4) => x0.dart_sqlite3_bind_text(x1,x2,x3,x4),
      _1682: (x0,x1,x2,x3,x4) => x0.dart_sqlite3_bind_blob(x1,x2,x3,x4),
      _1684: (x0,x1) => x0.sqlite3_column_count(x1),
      _1685: (x0,x1,x2) => x0.sqlite3_column_name(x1,x2),
      _1686: (x0,x1,x2) => x0.sqlite3_column_type(x1,x2),
      _1687: (x0,x1,x2) => x0.sqlite3_column_int64(x1,x2),
      _1688: (x0,x1,x2) => x0.sqlite3_column_double(x1,x2),
      _1689: (x0,x1,x2) => x0.sqlite3_column_bytes(x1,x2),
      _1690: (x0,x1,x2) => x0.sqlite3_column_text(x1,x2),
      _1691: (x0,x1,x2) => x0.sqlite3_column_blob(x1,x2),
      _1692: (x0,x1) => x0.sqlite3_value_type(x1),
      _1694: (x0,x1) => x0.sqlite3_value_int64(x1),
      _1695: (x0,x1) => x0.sqlite3_value_double(x1),
      _1696: (x0,x1) => x0.sqlite3_value_bytes(x1),
      _1697: (x0,x1) => x0.sqlite3_value_text(x1),
      _1698: (x0,x1) => x0.sqlite3_value_blob(x1),
      _1699: (x0,x1) => x0.sqlite3_result_null(x1),
      _1700: (x0,x1,x2) => x0.sqlite3_result_int64(x1,x2),
      _1701: (x0,x1,x2) => x0.sqlite3_result_double(x1,x2),
      _1702: (x0,x1,x2,x3,x4) => x0.sqlite3_result_text(x1,x2,x3,x4),
      _1703: (x0,x1,x2,x3,x4) => x0.sqlite3_result_blob64(x1,x2,x3,x4),
      _1704: (x0,x1,x2,x3) => x0.sqlite3_result_error(x1,x2,x3),
      _1705: (x0,x1,x2) => x0.sqlite3_result_subtype(x1,x2),
      _1708: (x0,x1) => x0.sqlite3_step(x1),
      _1709: (x0,x1) => x0.sqlite3_reset(x1),
      _1710: (x0,x1) => x0.sqlite3_changes(x1),
      _1711: (x0,x1) => x0.sqlite3_stmt_isexplain(x1),
      _1713: (x0,x1) => x0.sqlite3_last_insert_rowid(x1),
      _1730: (x0,x1,x2,x3) => x0.dart_sqlite3_register_vfs(x1,x2,x3),
      _1733: (x0,x1,x2,x3,x4,x5,x6) => x0.dart_sqlite3_create_function_v2(x1,x2,x3,x4,x5,x6),
      _1735: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1735(f,arguments.length,x0) }),
      _1736: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1736(f,arguments.length,x0,x1) }),
      _1737: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3,x4) { return module.exports._1737(f,arguments.length,x0,x1,x2,x3,x4) }),
      _1738: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1738(f,arguments.length,x0,x1,x2) }),
      _1739: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1739(f,arguments.length,x0,x1,x2,x3) }),
      _1740: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1740(f,arguments.length,x0,x1,x2,x3) }),
      _1741: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1741(f,arguments.length,x0,x1,x2) }),
      _1742: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1742(f,arguments.length,x0,x1) }),
      _1743: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1743(f,arguments.length,x0,x1) }),
      _1744: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1744(f,arguments.length,x0) }),
      _1745: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1745(f,arguments.length,x0,x1,x2,x3) }),
      _1746: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1746(f,arguments.length,x0,x1,x2,x3) }),
      _1747: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1747(f,arguments.length,x0,x1) }),
      _1748: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1748(f,arguments.length,x0,x1) }),
      _1749: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1749(f,arguments.length,x0,x1) }),
      _1750: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1750(f,arguments.length,x0,x1) }),
      _1751: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1751(f,arguments.length,x0,x1) }),
      _1752: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1752(f,arguments.length,x0,x1) }),
      _1753: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1753(f,arguments.length,x0) }),
      _1754: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1754(f,arguments.length,x0) }),
      _1755: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1755(f,arguments.length,x0) }),
      _1756: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3,x4) { return module.exports._1756(f,arguments.length,x0,x1,x2,x3,x4) }),
      _1757: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1757(f,arguments.length,x0,x1,x2,x3) }),
      _1758: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1758(f,arguments.length,x0,x1,x2,x3) }),
      _1759: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1759(f,arguments.length,x0,x1,x2,x3) }),
      _1760: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1760(f,arguments.length,x0,x1) }),
      _1761: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1761(f,arguments.length,x0,x1) }),
      _1762: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3,x4) { return module.exports._1762(f,arguments.length,x0,x1,x2,x3,x4) }),
      _1763: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1763(f,arguments.length,x0,x1) }),
      _1764: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1764(f,arguments.length,x0,x1) }),
      _1765: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1765(f,arguments.length,x0,x1,x2) }),
      _1766: (x0,x1,x2) => x0.instantiateStreaming(x1,x2),
      _1770: x0 => new URL(x0),
      _1771: (x0,x1) => new URL(x0,x1),
      _1772: (x0,x1) => globalThis.fetch(x0,x1),
      _1773: (x0,x1,x2) => x0.postMessage(x1,x2),
      _1774: (x0,x1,x2) => x0.postMessage(x1,x2),
      _1776: (x0,x1) => ({i: x0,p: x1}),
      _1777: (x0,x1) => ({c: x0,r: x1}),
      _1778: x0 => x0.i,
      _1779: x0 => x0.p,
      _1780: x0 => x0.c,
      _1781: x0 => x0.r,
      _1782: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1782(f,arguments.length,x0) }),
      _1783: (x0,x1) => x0.postMessage(x1),
      _1784: x0 => x0.close(),
      _1786: x0 => new Worker(x0),
      _1788: x0 => x0.getDirectory(),
      _1789: x0 => ({create: x0}),
      _1790: (x0,x1,x2) => x0.getFileHandle(x1,x2),
      _1791: x0 => x0.createSyncAccessHandle(),
      _1792: x0 => x0.close(),
      _1795: x0 => x0.close(),
      _1796: (x0,x1) => x0.deleteDatabase(x1),
      _1798: (x0,x1,x2) => x0.open(x1,x2),
      _1802: (x0,x1,x2) => x0.getDirectoryHandle(x1,x2),
      _1807: x0 => ({create: x0}),
      _1812: (x0,x1) => new SharedWorker(x0,x1),
      _1813: x0 => x0.start(),
      _1814: x0 => x0.terminate(),
      _1815: () => new MessageChannel(),
      _1818: (x0,x1) => x0.postMessage(x1),
      _1819: x0 => new SharedArrayBuffer(x0),
      _1820: x0 => ({at: x0}),
      _1821: x0 => x0.getSize(),
      _1822: (x0,x1) => x0.truncate(x1),
      _1823: x0 => x0.flush(),
      _1826: x0 => x0.synchronizationBuffer,
      _1827: x0 => x0.communicationBuffer,
      _1828: (x0,x1,x2,x3) => ({clientVersion: x0,root: x1,synchronizationBuffer: x2,communicationBuffer: x3}),
      _1829: (x0,x1) => globalThis.IDBKeyRange.bound(x0,x1),
      _1830: x0 => ({autoIncrement: x0}),
      _1831: (x0,x1,x2) => x0.createObjectStore(x1,x2),
      _1832: x0 => ({unique: x0}),
      _1833: (x0,x1,x2,x3) => x0.createIndex(x1,x2,x3),
      _1834: (x0,x1) => x0.createObjectStore(x1),
      _1835: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1835(f,arguments.length,x0) }),
      _1836: (x0,x1,x2) => x0.transaction(x1,x2),
      _1837: (x0,x1) => x0.objectStore(x1),
      _1839: (x0,x1) => x0.index(x1),
      _1840: x0 => x0.openKeyCursor(),
      _1841: (x0,x1) => x0.getKey(x1),
      _1842: (x0,x1) => ({name: x0,length: x1}),
      _1843: (x0,x1) => x0.put(x1),
      _1844: (x0,x1) => x0.get(x1),
      _1845: (x0,x1) => x0.openCursor(x1),
      _1846: x0 => globalThis.IDBKeyRange.only(x0),
      _1847: (x0,x1,x2) => x0.put(x1,x2),
      _1848: (x0,x1) => x0.update(x1),
      _1849: (x0,x1) => x0.delete(x1),
      _1850: x0 => x0.name,
      _1851: x0 => x0.length,
      _1854: x0 => x0.continue(),
      _1855: () => globalThis.indexedDB,
      _1856: () => globalThis.navigator,
      _1857: (x0,x1) => x0.read(x1),
      _1858: (x0,x1,x2) => x0.read(x1,x2),
      _1859: (x0,x1) => x0.write(x1),
      _1860: (x0,x1,x2) => x0.write(x1,x2),
      _1862: (x0,x1,x2) => globalThis.Atomics.wait(x0,x1,x2),
      _1864: (x0,x1,x2) => globalThis.Atomics.notify(x0,x1,x2),
      _1865: (x0,x1,x2) => globalThis.Atomics.store(x0,x1,x2),
      _1866: (x0,x1) => globalThis.Atomics.load(x0,x1),
      _1867: () => globalThis.Int32Array,
      _1869: () => globalThis.Uint8Array,
      _1871: () => globalThis.DataView,
      _1873: x0 => x0.byteLength,
      _1875: x0 => globalThis.BigInt(x0),
      _1876: x0 => globalThis.Number(x0),
      _1883: x0 => new BroadcastChannel(x0),
      _1884: x0 => globalThis.Array.isArray(x0),
      _1885: (x0,x1) => x0.postMessage(x1),
      _1886: x0 => x0.close(),
      _1887: (x0,x1) => ({kind: x0,table: x1}),
      _1888: x0 => x0.kind,
      _1889: x0 => x0.table,
      _1890: () => new XMLHttpRequest(),
      _1891: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1895: x0 => x0.send(),
      _1897: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1897(f,arguments.length,x0) }),
      _1898: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1898(f,arguments.length,x0) }),
      _1903: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1903(f,arguments.length,x0) }),
      _1904: (x0,x1) => x0.postMessage(x1),
      _1905: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1905(f,arguments.length,x0) }),
      _1906: x0 => x0.close(),
      _1911: (x0,x1) => x0.appendChild(x1),
      _1915: x0 => x0.trustedTypes,
      _1916: (x0,x1) => { x0.src = x1 },
      _1917: (x0,x1) => x0.createScriptURL(x1),
      _1918: x0 => x0.nonce,
      _1919: (x0,x1) => x0.debug(x1),
      _1920: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1920(f,arguments.length,x0) }),
      _1921: () => new AbortController(),
      _1922: x0 => x0.abort(),
      _1923: (x0,x1,x2,x3,x4,x5) => ({method: x0,headers: x1,body: x2,credentials: x3,redirect: x4,signal: x5}),
      _1924: (x0,x1) => globalThis.fetch(x0,x1),
      _1925: (x0,x1) => x0.get(x1),
      _1926: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1926(f,arguments.length,x0,x1,x2) }),
      _1927: (x0,x1) => x0.forEach(x1),
      _1928: x0 => x0.getReader(),
      _1929: x0 => x0.cancel(),
      _1930: x0 => x0.read(),
      _1932: (x0,x1) => { x0.data = x1 },
      _1933: (x0,x1) => { x0.scale = x1 },
      _1934: (x0,x1) => { x0.canvasContext = x1 },
      _1935: (x0,x1) => { x0.viewport = x1 },
      _1936: (x0,x1) => { x0.cMapUrl = x1 },
      _1937: (x0,x1) => { x0.cMapPacked = x1 },
      _1938: x0 => x0.promise,
      _1939: x0 => x0.numPages,
      _1940: x0 => x0.width,
      _1941: x0 => x0.height,
      _1942: x0 => x0.promise,
      _1943: o => o instanceof Array,
      _1944: (a, i) => a.push(i),
      _1945: (a, i) => a.splice(i, 1)[0],
      _1947: (a, l) => a.length = l,
      _1948: a => a.pop(),
      _1949: (a, i) => a.splice(i, 1),
      _1950: (a, s) => a.join(s),
      _1951: (a, s, e) => a.slice(s, e),
      _1952: (a, s, e) => a.splice(s, e),
      _1953: (a, b) => a == b ? 0 : (a > b ? 1 : -1),
      _1954: a => a.length,
      _1956: (a, i) => a[i],
      _1957: (a, i, v) => a[i] = v,
      _1959: o => {
        if (o instanceof ArrayBuffer) return 0;
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
          return 1;
        }
        return 2;
      },
      _1960: (o, offsetInBytes, lengthInBytes) => {
        var dst = new ArrayBuffer(lengthInBytes);
        new Uint8Array(dst).set(new Uint8Array(o, offsetInBytes, lengthInBytes));
        return new DataView(dst);
      },
      _1961: o => o instanceof DataView,
      _1962: o => o instanceof Uint8Array,
      _1963: (o, start, length) => new Uint8Array(o.buffer, o.byteOffset + start, length),
      _1964: o => o instanceof Int8Array,
      _1965: (o, start, length) => new Int8Array(o.buffer, o.byteOffset + start, length),
      _1966: o => o instanceof Uint8ClampedArray,
      _1967: (o, start, length) => new Uint8ClampedArray(o.buffer, o.byteOffset + start, length),
      _1968: o => o instanceof Uint16Array,
      _1969: (o, start, length) => new Uint16Array(o.buffer, o.byteOffset + start, length),
      _1970: o => o instanceof Int16Array,
      _1971: (o, start, length) => new Int16Array(o.buffer, o.byteOffset + start, length),
      _1972: o => o instanceof Uint32Array,
      _1973: (o, start, length) => new Uint32Array(o.buffer, o.byteOffset + start, length),
      _1974: o => o instanceof Int32Array,
      _1975: (o, start, length) => new Int32Array(o.buffer, o.byteOffset + start, length),
      _1976: (o, start, length) => new BigUint64Array(o.buffer, o.byteOffset + start, length),
      _1977: (o, start, length) => new BigInt64Array(o.buffer, o.byteOffset + start, length),
      _1978: o => o instanceof Float32Array,
      _1979: (o, start, length) => new Float32Array(o.buffer, o.byteOffset + start, length),
      _1980: o => o instanceof Float64Array,
      _1981: (o, start, length) => new Float64Array(o.buffer, o.byteOffset + start, length),
      _1982: (t, s) => t.set(s),
      _1983: l => new DataView(new ArrayBuffer(l)),
      _1984: (o) => new DataView(o.buffer, o.byteOffset, o.byteLength),
      _1985: o => o.byteLength,
      _1986: o => o.buffer,
      _1987: o => o.byteOffset,
      _1988: Function.prototype.call.bind(Object.getOwnPropertyDescriptor(DataView.prototype, 'byteLength').get),
      _1989: (b, o) => new DataView(b, o),
      _1990: (b, o, l) => new DataView(b, o, l),
      _1991: Function.prototype.call.bind(DataView.prototype.getUint8),
      _1992: Function.prototype.call.bind(DataView.prototype.setUint8),
      _1993: Function.prototype.call.bind(DataView.prototype.getInt8),
      _1994: Function.prototype.call.bind(DataView.prototype.setInt8),
      _1995: Function.prototype.call.bind(DataView.prototype.getUint16),
      _1996: Function.prototype.call.bind(DataView.prototype.setUint16),
      _1997: Function.prototype.call.bind(DataView.prototype.getInt16),
      _1998: Function.prototype.call.bind(DataView.prototype.setInt16),
      _1999: Function.prototype.call.bind(DataView.prototype.getUint32),
      _2000: Function.prototype.call.bind(DataView.prototype.setUint32),
      _2001: Function.prototype.call.bind(DataView.prototype.getInt32),
      _2002: Function.prototype.call.bind(DataView.prototype.setInt32),
      _2003: Function.prototype.call.bind(DataView.prototype.getBigUint64),
      _2004: Function.prototype.call.bind(DataView.prototype.setBigUint64),
      _2005: Function.prototype.call.bind(DataView.prototype.getBigInt64),
      _2006: Function.prototype.call.bind(DataView.prototype.setBigInt64),
      _2007: Function.prototype.call.bind(DataView.prototype.getFloat32),
      _2008: Function.prototype.call.bind(DataView.prototype.setFloat32),
      _2009: Function.prototype.call.bind(DataView.prototype.getFloat64),
      _2010: Function.prototype.call.bind(DataView.prototype.setFloat64),
      _2011: Function.prototype.call.bind(Number.prototype.toString),
      _2012: Function.prototype.call.bind(BigInt.prototype.toString),
      _2013: Function.prototype.call.bind(Number.prototype.toString),
      _2014: (d, digits) => d.toFixed(digits),
      _2025: () => globalThis.document,
      _2031: (x0,x1) => { x0.height = x1 },
      _2033: (x0,x1) => { x0.width = x1 },
      _2035: (x0,x1) => { x0.pointerEvents = x1 },
      _2044: x0 => x0.style,
      _2047: x0 => x0.src,
      _2048: (x0,x1) => { x0.src = x1 },
      _2049: x0 => x0.naturalWidth,
      _2050: x0 => x0.naturalHeight,
      _2066: x0 => x0.status,
      _2067: (x0,x1) => { x0.responseType = x1 },
      _2069: x0 => x0.response,
      _2070: () => globalThis.google.accounts.oauth2,
      _2071: (x0,x1,x2) => x0.hasGrantedAllScopes(x1,x2),
      _2084: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2084(f,arguments.length,x0) }),
      _2085: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2085(f,arguments.length,x0) }),
      _2086: (x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10) => ({client_id: x0,callback: x1,scope: x2,include_granted_scopes: x3,prompt: x4,enable_granular_consent: x5,enable_serial_consent: x6,login_hint: x7,hd: x8,state: x9,error_callback: x10}),
      _2087: x0 => x0.requestAccessToken(),
      _2090: x0 => x0.access_token,
      _2091: x0 => x0.expires_in,
      _2097: x0 => x0.error,
      _2098: x0 => x0.error_description,
      _2100: x0 => x0.type,
      _2101: x0 => x0.message,
      _2105: () => globalThis.google.accounts.id,
      _2119: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2119(f,arguments.length,x0) }),
      _2122: (x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16) => ({client_id: x0,auto_select: x1,callback: x2,login_uri: x3,native_callback: x4,cancel_on_tap_outside: x5,prompt_parent_id: x6,nonce: x7,context: x8,state_cookie_domain: x9,ux_mode: x10,allowed_parent_origin: x11,intermediate_iframe_close_callback: x12,itp_support: x13,login_hint: x14,hd: x15,use_fedcm_for_prompt: x16}),
      _2133: x0 => x0.error,
      _2135: x0 => x0.credential,
      _2146: x0 => { globalThis.onGoogleLibraryLoad = x0 },
      _2147: (module,f) => finalizeWrapper(f, function() { return module.exports._2147(f,arguments.length) }),
      _2196: (x0,x1) => { x0.responseType = x1 },
      _2197: x0 => x0.response,
      _2257: (x0,x1) => { x0.draggable = x1 },
      _2273: x0 => x0.style,
      _2286: (x0,x1) => { x0.oncancel = x1 },
      _2292: (x0,x1) => { x0.onchange = x1 },
      _2332: (x0,x1) => { x0.onerror = x1 },
      _2472: (x0,x1) => { x0.nonce = x1 },
      _2630: (x0,x1) => { x0.target = x1 },
      _2632: (x0,x1) => { x0.download = x1 },
      _2657: (x0,x1) => { x0.href = x1 },
      _3202: (x0,x1) => { x0.accept = x1 },
      _3216: x0 => x0.files,
      _3242: (x0,x1) => { x0.multiple = x1 },
      _3260: (x0,x1) => { x0.type = x1 },
      _3510: (x0,x1) => { x0.src = x1 },
      _3512: (x0,x1) => { x0.type = x1 },
      _3516: (x0,x1) => { x0.async = x1 },
      _3518: (x0,x1) => { x0.defer = x1 },
      _3554: x0 => x0.width,
      _3555: (x0,x1) => { x0.width = x1 },
      _3556: x0 => x0.height,
      _3557: (x0,x1) => { x0.height = x1 },
      _3960: x0 => x0.items,
      _3963: (x0,x1) => x0[x1],
      _3967: x0 => x0.length,
      _3973: x0 => x0.dataTransfer,
      _3977: () => globalThis.window,
      _4016: x0 => x0.document,
      _4038: x0 => x0.navigator,
      _4109: (x0,x1) => { x0.ondragenter = x1 },
      _4111: (x0,x1) => { x0.ondragleave = x1 },
      _4113: (x0,x1) => { x0.ondragover = x1 },
      _4117: (x0,x1) => { x0.ondrop = x1 },
      _4300: x0 => x0.trustedTypes,
      _4302: x0 => x0.localStorage,
      _4427: x0 => x0.userAgent,
      _4428: x0 => x0.vendor,
      _4433: x0 => x0.onLine,
      _4440: x0 => x0.storage,
      _4478: x0 => x0.data,
      _4508: x0 => x0.port1,
      _4509: x0 => x0.port2,
      _4511: (x0,x1) => { x0.onmessage = x1 },
      _4565: (x0,x1) => { x0.onmessage = x1 },
      _4576: (x0,x1) => { x0.onmessage = x1 },
      _4588: x0 => x0.port,
      _6527: x0 => x0.type,
      _6528: x0 => x0.target,
      _6568: x0 => x0.signal,
      _6577: x0 => x0.length,
      _6617: x0 => x0.baseURI,
      _6623: x0 => x0.firstChild,
      _6634: () => globalThis.document,
      _6714: x0 => x0.body,
      _6716: x0 => x0.head,
      _7045: (x0,x1) => { x0.id = x1 },
      _7069: (x0,x1) => { x0.innerHTML = x1 },
      _7072: x0 => x0.children,
      _7378: x0 => x0.clientX,
      _7379: x0 => x0.clientY,
      _8391: x0 => x0.value,
      _8393: x0 => x0.done,
      _8552: x0 => x0.size,
      _8553: x0 => x0.type,
      _8560: x0 => x0.name,
      _8561: x0 => x0.lastModified,
      _8566: x0 => x0.length,
      _8571: x0 => x0.result,
      _9067: x0 => x0.url,
      _9069: x0 => x0.status,
      _9071: x0 => x0.statusText,
      _9072: x0 => x0.headers,
      _9073: x0 => x0.body,
      _9085: x0 => x0.instance,
      _9087: () => globalThis.WebAssembly,
      _9109: x0 => x0.exports,
      _9117: x0 => x0.buffer,
      _10526: x0 => x0.result,
      _10527: x0 => x0.error,
      _10538: (x0,x1) => { x0.onupgradeneeded = x1 },
      _10540: x0 => x0.oldVersion,
      _10619: x0 => x0.key,
      _10620: x0 => x0.primaryKey,
      _10622: x0 => x0.value,
      _11460: (x0,x1) => { x0.display = x1 },
      _12682: x0 => x0.name,
      _13356: x0 => x0.isDirectory,
      _13357: x0 => x0.name,
      _13358: x0 => x0.fullPath,
      _13388: () => globalThis.console,

    };

    const baseImports = {
      dart2wasm: dart2wasm,
      Math: Math,
      Date: Date,
      Object: Object,
      Array: Array,
      Reflect: Reflect,
      WebAssembly: {
        JSTag: WebAssembly.JSTag,
      },
      "": new Proxy({}, { get(_, prop) { return prop; } }),

    };

    const jsStringPolyfill = {
      "charCodeAt": (s, i) => s.charCodeAt(i),
      "compare": (s1, s2) => {
        if (s1 < s2) return -1;
        if (s1 > s2) return 1;
        return 0;
      },
      "concat": (s1, s2) => s1 + s2,
      "equals": (s1, s2) => s1 === s2,
      "fromCharCode": (i) => String.fromCharCode(i),
      "length": (s) => s.length,
      "substring": (s, a, b) => s.substring(a, b),
      "fromCharCodeArray": (a, start, end) => {
        if (end <= start) return '';

        const read = dartInstance.exports.$wasmI16ArrayGet;
        let result = '';
        let index = start;
        const chunkLength = Math.min(end - index, 500);
        let array = new Array(chunkLength);
        while (index < end) {
          const newChunkLength = Math.min(end - index, 500);
          for (let i = 0; i < newChunkLength; i++) {
            array[i] = read(a, index++);
          }
          if (newChunkLength < chunkLength) {
            array = array.slice(0, newChunkLength);
          }
          result += String.fromCharCode(...array);
        }
        return result;
      },
      "intoCharCodeArray": (s, a, start) => {
        if (s === '') return 0;

        const write = dartInstance.exports.$wasmI16ArraySet;
        for (var i = 0; i < s.length; ++i) {
          write(a, start++, s.charCodeAt(i));
        }
        return s.length;
      },
      "test": (s) => typeof s == "string",
    };


    

    dartInstance = await WebAssembly.instantiate(this.module, {
      ...baseImports,
      ...additionalImports,
      
      "wasm:js-string": jsStringPolyfill,
    });
    dartInstance.exports.$setThisModule(dartInstance);

    return new InstantiatedApp(this, dartInstance);
  }
}

class InstantiatedApp {
  constructor(compiledApp, instantiatedModule) {
    this.compiledApp = compiledApp;
    this.instantiatedModule = instantiatedModule;
  }

  // Call the main function with the given arguments.
  invokeMain(...args) {
    this.instantiatedModule.exports.$invokeMain(args);
  }
}
